
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'node --experimental-strip-types prisma/seed.ts',
  },
  engine: "classic",
  // DATABASE_URL is required for migrate/db push but NOT for generate.
  // Using process.env directly (not env()) avoids a hard throw during build.
  datasource: {
    url: process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
