CREATE TABLE IF NOT EXISTS "RolePermissionPolicy" (
  "role" TEXT NOT NULL PRIMARY KEY,
  "grants" JSONB NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "updatedById" TEXT,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed the reviewed baseline once; never overwrite administrator changes.
INSERT INTO "RolePermissionPolicy" (role,grants,version) VALUES ('AMC_PRINCIPAL', '["brand.read","brand.create","brand.update","asset.read","asset.create","asset.update","asset.archive","draft.read","draft.create","draft.update","draft.submit","draft.approve","draft.reject","content.read","content.schedule","content.publish","content.retry","game.read","game.create","game.update","game.delete","analytics.read","review.read","review.reply","action_item.read","action_item.create","action_item.resolve","work_log.read","agent.read","agent.manage","content.dashboard.read","content.video-making.read","content.video-making.create","content.video-making.update","content.video-making.generate","content.video-making.delete","content.video-production.read","content.video-production.create","content.video-production.update","content.video-production.generate","content.video-production.delete","content.inspiration-library.read","content.inspiration-library.create","content.inspiration-library.update","content.inspiration-library.generate","content.inspiration-library.review","content.inspiration-library.publish","content.inspiration-library.delete","content.inspiration-library.export","content.inspiration-tags.read","content.inspiration-tags.create","content.inspiration-tags.update","content.inspiration-tags.review","content.inspiration-tags.generate","content.inspiration-tags.delete","content.content-lab.read","content.content-lab.update","content.content-lab.generate","content.skills.read","content.skills.update","content.knowledge.read","content.records.read","content.records.review"]'::jsonb, 1) ON CONFLICT (role) DO NOTHING;
INSERT INTO "RolePermissionPolicy" (role,grants,version) VALUES ('BRAND_OWNER', '["brand.read","brand.update","asset.read","asset.create","asset.update","asset.archive","draft.read","draft.create","draft.update","draft.submit","draft.approve","draft.reject","content.read","content.schedule","content.publish","content.retry","game.read","game.create","game.update","game.delete","analytics.read","review.read","review.reply","action_item.read","action_item.create","action_item.resolve","work_log.read"]'::jsonb, 1) ON CONFLICT (role) DO NOTHING;
INSERT INTO "RolePermissionPolicy" (role,grants,version) VALUES ('BD', '["brand.read","brand.create","subscription.read","subscription.manage"]'::jsonb, 1) ON CONFLICT (role) DO NOTHING;
INSERT INTO "RolePermissionPolicy" (role,grants,version) VALUES ('RESEARCHER', '["brand.read","content.dashboard.read","content.inspiration-library.read","content.inspiration-library.create","content.inspiration-library.export","content.inspiration-tags.read"]'::jsonb, 1) ON CONFLICT (role) DO NOTHING;
