export const SUBSCRIPTION_TERMS_VERSION = 'AMC-SMSA-v1.02'

export const SUBSCRIPTION_TERMS_TITLE = 'AMC Digital Marketing Service Terms / AMC 数字营销服务条款'

export const SUBSCRIPTION_TERMS_FULL_TEXT = `
AMC - Your AI Marketing Crew
Deliverychinatown Pte. Ltd. | amc.immedi.ai
Version: AMC-SMSA-v1.02 | Updated: 14 July 2026

Digital Marketing Service Terms
数字营销服务条款

This agreement is generated by the AMC subscription workflow. Contract number, package, term, fees and signing date are determined by the submitted order, accepted quotation, invoice, statement of work or written confirmation.
本协议由 AMC 订阅流程生成。合同编号、套餐、期限、费用及签署日期，以提交的订单、已接受的报价、发票、工作说明或书面确认为准。

This agreement is governed by the laws of Singapore.
本协议受新加坡法律管辖。

1. Parties / 合同主体
Customer: the SME, brand owner or authorised representative subscribing to AMC services.
客户：订阅 AMC 服务的 SME、品牌方或其授权代表。
Vendor: DeliveryChinatown Pte. Ltd., service brand AMC - Your AI Marketing Crew.
供应商：DeliveryChinatown Pte. Ltd.，服务品牌为 AMC - Your AI Marketing Crew。

2. Service Description / 服务说明
AMC is a digital marketing management solution that supports brand workspace setup, digital marketing needs analysis, strategy development, campaign workflow, AI-assisted content generation, media asset management, review and approval workflow, reporting, recommendations and handover documentation.
AMC 是数字营销管理方案，支持品牌工作区设置、数字营销需求分析、策略制定、营销活动流程、AI 辅助内容生成、素材管理、审核批准流程、报告、优化建议和交接文档。

3. Package Scope / 套餐范围
The exact package, subscription term, deliverables, platform coverage, usage limits, fees, add-ons and payment milestones are stated in the accepted quotation, order, Annex 3, invoice or statement of work.
具体套餐、订阅期限、交付内容、覆盖平台、使用限制、费用、附加服务和付款节点，以已接受的报价、订单、Annex 3、发票或工作说明为准。

4. PSG Programme Context / PSG 项目背景
If the Customer intends to apply for PSG support, the Customer remains responsible for its own PSG application, eligibility, declarations, supporting documents and grant compliance. AMC may provide supporting documents such as quotation, invoice, usage report, product information and screenshot evidence. PSG approval and claim outcome are determined by the relevant government agency and are not guaranteed by AMC.
如客户计划申请 PSG 补贴，客户仍需自行负责 PSG 申请、资格、声明、支持文件和补贴合规。AMC 可协助提供报价单、发票、使用报告、产品资料和截图证据。PSG 获批及报销结果由相关政府机构决定，AMC 不作保证。

5. Customer and User Obligations / 客户与用户义务
The Customer must provide accurate company, brand, outlet, product, pricing, promotion, menu, service and contact information; provide timely access, permissions, materials and approvals; ensure approving users are authorised; ensure customer-supplied materials are owned or properly licensed; inform AMC of restricted claims or regulated content; avoid uploading unnecessary sensitive personal data; maintain account security; and pay approved fees, taxes and non-supportable third-party costs.
客户须提供准确的公司、品牌、门店、产品、价格、促销、菜单、服务和联系方式；及时提供账号权限、素材和审批；确保审批人已获授权；确保客户提供的素材自有或已合法授权；提前告知受限制或受监管的内容；避免上传不必要的敏感个人数据；维护账号安全；并支付已确认费用、税费及不受补贴支持的第三方费用。

6. Content Approval and Publishing / 内容审批与发布
Unless an autopilot or pre-approved publishing mode is expressly agreed in writing, all AI-generated or operator-prepared content is draft content until approved by the Customer or an authorised representative. The Customer is responsible for checking factual accuracy, offer validity, pricing, promotion terms, compliance requirements and suitability before approval.
除非双方书面同意自动发布或预批准发布模式，所有 AI 生成或运营人员准备的内容，在客户或授权代表批准前均为草稿。客户负责在批准前核对事实准确性、优惠有效性、价格、促销条款、合规要求和适用性。

7. Third-Party Platforms / 第三方平台
AMC may support workflows for Google Business Profile, Instagram, Facebook, TikTok, WhatsApp, websites, booking links, analytics tools and other third-party platforms. These terms are between AMC and the Customer only. AMC is not responsible for third-party outages, policy enforcement, account suspensions, API changes, data delays or platform decisions. The Customer remains responsible for complying with third-party platform terms.
AMC 可支持 Google Business Profile、Instagram、Facebook、TikTok、WhatsApp、网站、预订链接、数据分析工具等第三方平台流程。本条款仅适用于 AMC 与客户之间。AMC 不对第三方平台故障、政策执行、账号限制、API 变化、数据延迟或平台决定负责。客户仍需遵守第三方平台条款。

8. Fees and Excluded Costs / 费用与排除项目
Fees, payment milestones and billing frequency are stated in the accepted quotation, order form or invoice. Advertising media spend, PPC, ad buys, boosted posts, purchase of likes/followers, influencer/KOL/creator fees, gifts, meals, transport, outbound marketing, purchased databases, third-party hosting, maintenance, SSL, domain fees, hardware, livestreaming equipment, third-party training courses, platform subscriptions and payment processing fees are excluded unless separately stated.
费用、付款节点和账单频率以已接受的报价、订单或发票为准。广告费、PPC、投流、boosted posts、购买点赞/粉丝、达人/KOL/创作者费用、礼品、餐费、交通费、外呼营销、购买数据库、第三方托管、维护、SSL、域名、硬件、直播设备、第三方培训课程、平台订阅和支付处理费均不包含，除非另有单独列明。

9. Add-On Services / 附加服务
Add-on services such as professional on-site content shooting, KOL distribution, multi-outlet support, Dianping operations, ordering/booking site support or customised services are included only if stated in the quotation or order form. If an add-on is not supportable under PSG, it will be separately stated and borne by the Customer.
专业到店拍摄、KOL 分发、多门店支持、大众点评运营、点餐/预订网站支持或定制服务等附加服务，仅在报价或订单中列明时才包含。如附加服务不受 PSG 支持，将单独列明并由客户承担。

10. Reports and Handover / 报告与交接
AMC may provide usage reports, campaign reports, digital asset logs, published content references, analytics summaries and handover checklists. Upon completion or termination, subject to payment of outstanding fees, AMC will provide reasonable handover of approved strategy documents, campaign reports, customer-owned assets, published content logs and relevant platform access notes where applicable.
AMC 可提供使用报告、活动报告、数字资产记录、已发布内容链接、数据摘要和交接清单。项目完成或终止时，在结清应付费用后，AMC 将合理交接已批准的策略文件、活动报告、客户自有资产、已发布内容记录和相关平台访问说明。

11. Intellectual Property / 知识产权
Customer-supplied materials remain owned by the Customer or its licensors. Final approved campaign materials specifically created for the Customer under the paid package may be used by the Customer for its own business. AMC retains ownership of its platform, software, templates, workflows, prompts, methodologies, reusable frameworks, know-how, internal tools and pre-existing materials.
客户提供的素材仍归客户或其授权方所有。付费套餐下专为客户制作并最终确认的营销内容，客户可用于自身业务。AMC 保留平台、软件、模板、工作流、提示词、方法论、可复用框架、经验、内部工具和既有材料的所有权。

12. Confidentiality and Personal Data / 保密与个人数据
Both parties must keep confidential non-public business information, commercial terms, reports, credentials, customer data and operational records. Where personal data is processed, both parties must comply with applicable personal data protection laws, including Singapore PDPA where applicable.
双方应保护非公开商业信息、商业条款、报告、凭证、客户数据和运营记录。涉及个人数据处理时，双方应遵守适用的个人数据保护法律，包括适用的新加坡 PDPA。

13. Support, Changes and Revisions / 支持、变更与修改
Standard support covers normal product usage, workflow assistance, package clarification and reasonable troubleshooting. If no revision limit is stated in the quotation, up to 2 revision rounds per campaign asset are included. Additional revisions, major changes, urgent turnaround, new scope or changes caused by late Customer input may require a change request and additional fees.
标准支持包括正常产品使用、流程协助、套餐解释和合理故障排查。如报价未注明修改次数，每个营销资产包含最多 2 轮修改。额外修改、重大策略变化、紧急交付、新范围或客户延迟输入导致的变更，可能需要变更请求和额外费用。

14. Refunds, Cancellation and Termination / 退款、取消与终止
Refunds and cancellations are handled according to the accepted quotation, order form and applicable law. Fees for work already performed, activated subscription periods, completed reports, completed onboarding and delivered assets are non-refundable unless otherwise stated. AMC may suspend service for non-payment, misuse, security risk or breach after reasonable notice where practicable.
退款和取消以已接受的报价、订单和适用法律为准。已完成工作、已激活订阅期、已完成报告、已完成 onboarding 和已交付资产的费用原则上不退款，除非另有约定。如发生未付款、误用、安全风险或违约，AMC 可在合理可行情况下通知后暂停服务。

15. No Guaranteed Outcomes / 结果免责声明
AMC will use reasonable care and skill but does not guarantee sales, revenue, profit, ROAS, conversion, reach, followers, likes, engagement, search ranking, Google Maps ranking, review score improvement, PSG approval or third-party platform performance. KPIs are campaign targets or measurement references, not guaranteed results unless expressly stated in writing.
AMC 将以合理谨慎和技能提供服务，但不保证销售额、收入、利润、ROAS、转化、触达、粉丝、点赞、互动、搜索排名、Google Maps 排名、评分提升、PSG 获批或第三方平台表现。除非书面明确约定，KPI 为活动目标或衡量参考，不代表保证结果。

16. Limitation of Liability / 责任限制
To the fullest extent permitted by law, AMC's total liability arising from or relating to the service is limited to the fees paid by the Customer for the affected package during the 3 months immediately before the event giving rise to the claim. AMC is not liable for indirect, consequential, special, punitive or loss-of-profit damages.
在法律允许的最大范围内，AMC 因服务产生或相关的总责任，以客户在引发索赔事件前 3 个月内就受影响套餐向 AMC 支付的费用为限。AMC 不承担间接、后果性、特殊、惩罚性或利润损失责任。

17. Acceptance / 接受
The Customer accepts these terms by signing the quotation, order form or service agreement, confirming acceptance in writing, ticking the agreement checkbox, submitting a subscription order or continuing to use the service.
客户通过签署报价、订单或服务协议、书面确认、勾选同意框、提交订阅订单或继续使用服务，即表示接受本条款。
`.trim()

export const SUBSCRIPTION_TERMS_NOTICE =
  'Please read the full service terms and tick to agree before creating a payment order. 请完整阅读服务条款并勾选同意，方可创建支付订单。'
