import fs from "fs";
import path from "path";
import { prisma } from "../../lib/prisma.ts";
import { postfastPublish } from "../../lib/integrations/postfast.ts";
import { extractTopicKeywords } from "../../lib/topicExtractor.ts";

/**
 * 萃取草稿主题关键词，写入 topicKeywords 字段。
 * 注意：重复主题检测由 Scheduler 定时巡检（07:00/14:00）负责，不在此处实时检查。
 */
function enrichDraftData(caption: string): { topicKeywords: string[] } {
  return { topicKeywords: extractTopicKeywords(caption) }
}

export async function publisherNode(state: any) {
  console.log("=== PublisherNode Running ===");
  if (state.status === "pending" || state.status === "failed") {
    return state;
  }
  const { brandId, taskId, platform, caption, mediaUrls, hashtags, copywriteOnly } = state;

  if (!brandId || !taskId) {
    throw new Error("Missing brandId or taskId in state.");
  }

  // 1. Fetch task and brand details
  const task = await prisma.workUnit.findUnique({
    where: { id: taskId }
  });

  const brand = await prisma.brand.findUnique({
    where: { id: brandId },
    select: {
      postfastApiKey: true,
      name: true
    }
  });

  if (!brand) {
    throw new Error(`Brand ${brandId} not found.`);
  }

  // Extract draft ID if present
  let existingDraftId = state.draftId || null;
  if (!existingDraftId && task) {
    if (task.description) {
      const match = task.description.match(/(?:草稿|Draft)\s*ID:\s*([a-z0-9]{25,})/i);
      if (match) {
        existingDraftId = match[1];
      }
    }
    if (!existingDraftId && task.materials) {
      const match = task.materials.match(/(?:草稿|Draft)\s*ID:\s*([a-z0-9]{25,})/i);
      if (match) {
        existingDraftId = match[1];
      }
    }
  }

  if (state.aiFailed) {
    console.log(`AI Copywriting failed for task ${taskId}. Setting draft ${existingDraftId} status to failed.`);
    if (existingDraftId) {
      try {
        // Clean up assets generated by the designer for this draft/task
        const assetRefs = await prisma.contentAssetRef.findMany({
          where: { draftId: existingDraftId },
          include: { asset: true }
        });
        for (const ref of assetRefs) {
          const asset = ref.asset;
          if (asset && (asset.sourceType === 'designer' || asset.sourceType === 'postfast' || asset.sourceType === 'huawei_obs' || asset.aiCategory === 'optimized_media' || asset.aiCategory === 'watermarked_cover')) {
            const otherRefs = await prisma.contentAssetRef.count({
              where: { assetId: asset.id, draftId: { not: existingDraftId } }
            });
            if (otherRefs === 0) {
              await prisma.mediaAsset.delete({ where: { id: asset.id } });
              // Physically delete local file
              if (asset.url.startsWith("/uploads/")) {
                const localPath = path.join(process.cwd(), "public", asset.url);
                if (fs.existsSync(localPath)) {
                  fs.unlinkSync(localPath);
                }
              }
              console.log(`Deleted failed draft asset from DB: ${asset.id}`);
            }
          }
        }

        await prisma.actionItem.deleteMany({
          where: { draftId: existingDraftId }
        });
        await prisma.contentAssetRef.deleteMany({
          where: { draftId: existingDraftId }
        });
        
        const failureReason = state.complianceReason || state.error || "AI Copywriting failed";
        await prisma.contentDraft.update({
          where: { id: existingDraftId },
          data: {
            status: "failed",
            agentNote: failureReason
          }
        });
        console.log(`Updated failed draft ${existingDraftId} to failed status.`);
      } catch (e) {
        console.warn(`Failed to update failed draft status ${existingDraftId}:`, e);
      }
    }
    await prisma.workUnit.update({
      where: { id: taskId },
      data: {
        status: "failed",
        requiredInput: `AI Copywriting failed.`
      }
    });
    return {
      status: "failed",
      error: "AI Copywriting failed"
    };
  }

  const cleanHashtags = hashtags || [];
  const fullCaption = `${caption}\n\n${cleanHashtags.map((h: string) => h.startsWith('#') ? h : `#${h}`).join(" ")}`;

  if (copywriteOnly) {
    console.log("Publisher Node: copywriteOnly is true. Updating draft caption and hashtags, and completing task.");
    if (existingDraftId) {
      const draft = await prisma.contentDraft.findUnique({
        where: { id: existingDraftId }
      });
      if (draft) {
        await prisma.contentDraft.update({
          where: { id: existingDraftId },
          data: {
            caption: fullCaption,
            hashtags: cleanHashtags
          }
        });
        console.log(`Updated draft ${existingDraftId} caption and hashtags.`);
      }
    }

    await prisma.workUnit.update({
      where: { id: taskId },
      data: {
        status: "done",
        requiredInput: `AI Copywriting completed successfully.`
      }
    });

    return {
      publishedUrl: existingDraftId ? `manual://${platform}/${existingDraftId}` : "",
      status: "done"
    };
  }

  const dbPlatformId = platform === "red" || platform === "xhs" ? "xiaohongshu"
                     : platform === "google_business" ? "google_maps"
                     : platform;

  // 2. Fetch or create a social account record for logging
  let socialAccount = await prisma.socialAccount.findFirst({
    where: {
      brandId,
      platformId: dbPlatformId
    }
  });

  if (!socialAccount) {
    console.log(`No social account found for brand ${brandId} on ${dbPlatformId}. Creating a mock account.`);
    socialAccount = await prisma.socialAccount.create({
      data: {
        brandId,
        platformId: dbPlatformId,
        handle: "mock_" + dbPlatformId + "_handle",
        displayName: "Mock " + (platform === "red" || platform === "xhs" || platform === "xiaohongshu" ? "小红书" : platform === "google_business" || platform === "google_maps" ? "Google Business" : platform) + " Account",
        autoPilot: true
      }
    });
  }

  const isMockAccount = socialAccount.handle?.startsWith("mock_") || !brand.postfastApiKey;
  const isManualPlatform = platform === "red" || platform === "xiaohongshu";

  // 3. Execute publishing via PostFast if API Key is configured and account is connected and supports auto-publish
  if (brand.postfastApiKey && !isMockAccount && !isManualPlatform) {
    console.log(`Brand ${brand.name} has PostFast API key. Initiating actual social media publish...`);
    try {
      const publishRes = await postfastPublish({
        apiKey: brand.postfastApiKey,
        platform,
        caption,
        mediaUrls: mediaUrls || [],
        hashtags: cleanHashtags,
        accountId: socialAccount.id
      });

      if (publishRes.success) {
        const publishedUrl = publishRes.url || `https://www.${platform}.com/p/amc_mock_${Date.now()}`;
        console.log(`PostFast Publish Success! Post ID: ${publishRes.postId}, URL: ${publishedUrl}`);

        // Log the published draft
        let draftRecord;
        if (existingDraftId) {
          try {
            draftRecord = await prisma.contentDraft.update({
              where: { id: existingDraftId },
              data: {
                accountId: socialAccount.id,
                caption: fullCaption,
                mediaUrls: mediaUrls || [],
                hashtags: cleanHashtags,
                status: "published",
                platformPostId: publishRes.postId || "post_" + Date.now(),
                postUrl: publishRes.url || null,
                publishedAt: new Date()
              }
            });
            console.log(`Updated existing draft ${existingDraftId} to published.`);
          } catch (e) {
            console.warn(`Failed to update existing draft ${existingDraftId} to published, fallback to create.`, e);
          }
        }

        if (!draftRecord) {
          const enriched = enrichDraftData(fullCaption)
          draftRecord = await prisma.contentDraft.create({
            data: {
              brandId,
              accountId: socialAccount.id,
              caption: fullCaption,
              mediaUrls: mediaUrls || [],
              hashtags: cleanHashtags,
              status: "published",
              platformPostId: publishRes.postId || "post_" + Date.now(),
              postUrl: publishRes.url || null,
              publishedAt: new Date(),
              topicKeywords: enriched.topicKeywords,
            }
          });
        }

        // Update the Kanban WorkUnit to done
        await prisma.workUnit.update({
          where: { id: taskId },
          data: {
            status: "done",
            requiredInput: `Published successfully via PostFast at: ${publishedUrl}`
          }
        });

        return {
          publishedUrl,
          status: "done"
        };
      } else {
        console.error(`PostFast Publish Failed: ${publishRes.error}`);
        
        // Log draft with failed status
        let draftRecord;
        if (existingDraftId) {
          try {
            draftRecord = await prisma.contentDraft.update({
              where: { id: existingDraftId },
              data: {
                accountId: socialAccount.id,
                caption: fullCaption,
                mediaUrls: mediaUrls || [],
                hashtags: cleanHashtags,
                status: "failed",
                agentNote: `PostFast Publish Failed: ${publishRes.error || "Unknown error"}`
              }
            });
            console.log(`Updated existing draft ${existingDraftId} to failed.`);
          } catch (e) {
            console.warn(`Failed to update existing draft ${existingDraftId} to failed, fallback to create.`, e);
          }
        }

        if (!draftRecord) {
          const enriched = enrichDraftData(fullCaption)
          await prisma.contentDraft.create({
            data: {
              brandId,
              accountId: socialAccount.id,
              caption: fullCaption,
              mediaUrls: mediaUrls || [],
              hashtags: cleanHashtags,
              status: "failed",
              agentNote: `PostFast Publish Failed: ${publishRes.error || "Unknown error"}`,
              topicKeywords: enriched.topicKeywords,
            }
          });
        }

        // Keep task pending and report error
        await prisma.workUnit.update({
          where: { id: taskId },
          data: {
            status: "pending",
            requiredInput: `Publishing failed via PostFast: ${publishRes.error || "Unknown error"}. Please review.`
          }
        });

        return {
          error: publishRes.error || "Publishing failed via PostFast",
          status: "failed"
        };
      }
    } catch (err: any) {
      console.error("Error during PostFast publishing process:", err);

      await prisma.workUnit.update({
        where: { id: taskId },
        data: {
          status: "pending",
          requiredInput: `Internal error during publishing: ${err.message || String(err)}`
        }
      });

      return {
        error: err.message || String(err),
        status: "failed"
      };
    }
  }

  // 4. Manual / mockup draft generation flow
  const platformNameMap: Record<string, string> = {
    red: "小红书",
    xiaohongshu: "小红书",
    instagram: "Instagram",
    facebook: "Facebook",
    tiktok: "TikTok",
    google_business: "Google Business"
  };
  const readablePlatform = platformNameMap[platform] || platform;

  console.log(`Platform ${platform} is unlinked or requires manual publishing. Generating draft.`);
  
  let draft;
  if (existingDraftId) {
    try {
      draft = await prisma.contentDraft.update({
        where: { id: existingDraftId },
        data: {
          accountId: socialAccount.id,
          caption: fullCaption,
          mediaUrls: mediaUrls || [],
          hashtags: cleanHashtags,
          status: "draft",
          agentNote: `【手动发布提醒】此内容已更新。由于 ${readablePlatform} 账号未联通，请在草稿中手动复制发布。`
        }
      });
      console.log(`ContentDraft ${existingDraftId} updated in-place successfully.`);
    } catch (e) {
      console.warn(`Failed to update existing draft ${existingDraftId}, fallback to create.`, e);
    }
  }

  if (!draft) {
    const enriched = enrichDraftData(fullCaption)
    const manualNote = `【手动发布提醒】此内容已生成。由于 ${readablePlatform} 账号未联通，请在草稿中手动复制发布。`
    draft = await prisma.contentDraft.create({
      data: {
        brandId,
        accountId: socialAccount.id,
        caption: fullCaption,
        mediaUrls: mediaUrls || [],
        hashtags: cleanHashtags,
        status: "draft",
        agentNote: manualNote,
        topicKeywords: enriched.topicKeywords,
      }
    });
  }

  await prisma.workUnit.update({
    where: { id: taskId },
    data: {
      status: "done",
      requiredInput: `Draft generated for manual publishing on ${readablePlatform}. Please review and copy it from the Drafts page: ${draft.id}`
    }
  });

  console.log(`WorkUnit ${taskId} successfully closed and marked as done. Draft ID: ${draft.id}`);

  return {
    publishedUrl: `manual://${platform}/${draft.id}`,
    status: "done"
  };
}
