ALTER TABLE "LLMConfig"
  ADD COLUMN IF NOT EXISTS "capabilities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "timeoutMs" INTEGER NOT NULL DEFAULT 120000,
  ADD COLUMN IF NOT EXISTS "maxRetries" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "fallbackProfileIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "costMetadata" JSONB,
  ADD COLUMN IF NOT EXISTS "secretRef" TEXT;
