'use client'
import { useEffect, useState } from 'react'
import ModelVersionEditor from './ModelVersionEditor'
import { modelCapabilityLabels, modelUses, taskLabel, filterModels, groupIssues } from './modelManagementView'
export { modelCapabilityLabels } from './modelManagementView'
import { assertMediaModel } from '@/lib/model-management/executionContract'
const empty={defaults:{},exceptions:{}}
const button='rounded-lg border border-slate-200 dark:border-slate-700 px-3 py-2 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 disabled:opacity-40 disabled:cursor-not-allowed'
const primary=button+' bg-blue-600 text-white hover:bg-blue-700 dark:hover:bg-blue-700'
const input='w-full min-w-0 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-950 px-3 py-2 text-sm'
const panel='rounded-xl border border-slate-200 dark:border-slate-700 p-4 min-w-0'
const tabs=['使用配置','模型目录','诊断与记录']
const date=(v:any)=>v?new Date(v).toLocaleString('zh-CN'):'暂无记录'
export default function UnifiedModelManagement(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState<any>(null)
 const [tab,setTab]=useState(0),[editor,setEditor]=useState<any>(undefined),[exceptionTask,setExceptionTask]=useState('content:video_generation'),[exceptionModel,setExceptionModel]=useState('')
 const [filters,setFilters]=useState({search:'',provider:'',capability:'',status:''}),[page,setPage]=useState(1)
 const selection=data?.draft?.configuration||data?.current?.selection||empty
 async function load(){const r=await fetch('/api/admin/models',{cache:'no-store'}),v=await r.json().catch(()=>null);if(!r.ok||!v)throw new Error(v?.error||'配置服务不可用，请检查部署和数据库迁移');setData(v)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 async function action(action:string,extra:any={}){
  setBusy(true);setError('');setReport(null)
  try{const r=await fetch('/api/admin/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,expectedRevision:data?.draft?.revision||0,...extra})}),v=await r.json().catch(()=>null)
   if(!r.ok||!v)throw new Error(v?.error||'配置操作失败')
   if(action==='save-model')setEditor(undefined)
   await load();setReport(action==='validate'?v:null);return true
  }catch(e){setError(e instanceof Error?e.message:'操作失败');return false}finally{setBusy(false)}
 }
 const models:any[]=data?.models||[],connections:any[]=data?.connections||[],init=data?.draft?.initializationReport
 const superseded=new Set(models.map(m=>m.definition.previousModelId).filter(Boolean)),issues=groupIssues(init?.issues||[])
 const filtered=filterModels(models,connections,data?.current?.selection,selection,filters),pages=Math.max(1,Math.ceil(filtered.length/12)),currentPage=Math.min(page,pages)
 const latest=data?.validations?.[0],latestReport=report||latest?.report
 const saveSelection=(s:any)=>action('save-draft',{selection:s})
 const modelName=(id:any)=>models.find(m=>m.id===id)?.definition.name||(id?String(id):'未配置')
 const changeFilter=(key:string,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(1)}
 const eligible=(m:any,task:string)=>{if(task==='text')return true;try{assertMediaModel(task,{...m,protocol:connections.find(c=>c.id===m.connectionId)?.protocol});return true}catch{return false}}
 const selectDefault=(cap:string)=>{const changed=data.current.active&&selection.defaults[cap]!==data.current.selection?.defaults?.[cap];return <div key={cap} className={`min-w-0 space-y-2 ${changed?'border-l-2 border-blue-500 pl-3':''}`}><h4 className="text-sm font-semibold">{modelCapabilityLabels[cap]} <span className="text-xs text-slate-500">{cap==='text'?'Kanban':'Content'} 执行</span> {changed&&<span className="text-xs text-blue-600">有修改</span>}</h4><p className="text-xs text-slate-500 break-words">当前生效：{data.current.active?modelName(data.current.selection?.defaults?.[cap]):'业务沿用旧配置'}</p><label className="block text-xs text-slate-500">草稿选择<select aria-label={`${modelCapabilityLabels[cap]}默认模型`} disabled={busy} className={input+' mt-1 text-slate-900 dark:text-slate-100'} value={selection.defaults[cap]||''} onChange={e=>{const defaults={...selection.defaults};if(e.target.value)defaults[cap]=e.target.value;else delete defaults[cap];void saveSelection({...selection,defaults})}}><option value="">未配置</option>{models.filter(m=>m.definition.isEnabled!==false&&m.definition.capabilities.includes(cap)&&(eligible(m,cap)||selection.defaults[cap]===m.id)&&(!superseded.has(m.id)||selection.defaults[cap]===m.id)).map(m=><option key={m.id} value={m.id}>{!eligible(m,cap)?'[缺少执行适配] ':''}{m.definition.name} / {m.definition.modelName} · {m.connectionId.slice(0,8)}</option>)}</select></label></div>}
 return <section className="min-w-0 rounded-2xl border border-slate-200 bg-white text-slate-900 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-100">
  <header className="p-5 space-y-3 border-b border-slate-200 dark:border-slate-800"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-black text-lg">统一模型管理</h2><span className="text-xs text-slate-500 self-center">Kanban / Content / MM</span></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-500"><span>生效版本：{data?.current?.active?`v${data.current.version}`:'尚未发布'}</span><span>草稿：{data?.draft?`r${data.draft.revision} · 已保存`:'尚未初始化'}</span>{['kanban','content','mm'].map(system=><span key={system}>{system.toUpperCase()} 最近预检：{latestReport?.checks?.[`system.${system}`]===undefined?'未预检':latestReport.checks[`system.${system}`]?'通过':'未通过'}</span>)}</div>{!!issues.length&&<button className="text-sm text-amber-800 dark:text-amber-300 text-left" onClick={()=>setTab(2)}>{new Set(issues.map(g=>g.category)).size} 类问题阻止发布 · 查看并处理</button>}{!!init?.pending?.length&&<button className="block text-xs text-slate-500" onClick={()=>setTab(2)}>待配置 {init.pending.length} 项 · 不阻塞发布</button>}</header>
  <div role="tablist" aria-label="模型管理" className="flex border-b border-slate-200 dark:border-slate-800 px-3">{tabs.map((label,i)=><button key={label} id={`model-tab-${i}`} role="tab" aria-selected={tab===i} aria-controls={`model-panel-${i}`} tabIndex={tab===i?0:-1} className={`px-3 sm:px-5 py-3 text-sm whitespace-nowrap border-b-2 ${tab===i?'border-blue-600 text-blue-600 font-bold':'border-transparent text-slate-500'}`} onClick={()=>setTab(i)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();setTab(next);document.getElementById(`model-tab-${next}`)?.focus()}}>{label}</button>)}</div>
  {error&&<div role="alert" className="m-4 rounded-xl bg-red-50 text-red-700 p-3 text-sm break-words">{error}<button className={button+' ml-2'} disabled={busy} onClick={()=>{setReport(null);setError('');load().catch(e=>setError(e.message))}}>重新读取</button></div>}
  {!data&&!error&&<p role="status" className="p-6">正在读取模型配置…</p>}
  {data&&<div id={`model-panel-${tab}`} role="tabpanel" aria-labelledby={`model-tab-${tab}`} className="min-w-0 p-4 sm:p-5 space-y-5">
   {tab===0&&<>
    <p className="text-xs text-slate-500">保存只更新草稿；通过预检并发布后，新任务才使用新版本。</p>
    {!data.draft&&!data.current.active&&<div className={panel}><p className="text-sm mb-3">先读取已有模型和连接，无需重复填写密钥。</p><button className={primary} disabled={busy} onClick={()=>action('import')}>初始化已有配置</button></div>}
    <div className={panel+' bg-blue-50/50 dark:bg-blue-950/20 border-blue-200'}><p className="text-xs text-blue-600 mb-3">Kanban、Content、MM 共用一个文本模型</p>{selectDefault('text')}</div>
    <div className="grid lg:grid-cols-2 gap-4">{[['图片与视频',['image_understanding','video_understanding','image_generation','video_generation']],['语音与音乐',['speech_recognition','speech_synthesis','music']]].map(([title,caps])=><section key={String(title)} className={panel+' space-y-5'}><h3 className="font-bold text-sm">{title}</h3>{(caps as string[]).map(selectDefault)}</section>)}</div>
    <details className={panel}><summary className="cursor-pointer font-semibold text-sm">媒体任务例外 · {Object.keys(selection.exceptions).length} 项</summary><p className="text-xs text-slate-500 my-3">媒体优先使用任务例外，再使用能力默认模型；纯文本不能设置例外。</p><fieldset disabled={busy} className="space-y-3"><div className="grid md:grid-cols-[1fr_1fr_auto] gap-2"><input aria-label="媒体任务例外" className={input} value={exceptionTask} onChange={e=>setExceptionTask(e.target.value)}/><select aria-label="例外模型" className={input} value={exceptionModel} onChange={e=>setExceptionModel(e.target.value)}><option value="">选择媒体模型</option>{models.filter(m=>m.definition.isEnabled!==false&&m.definition.capabilities.some((c:string)=>c!=='text')&&eligible(m,exceptionTask.split(':')[1])).map(m=><option key={m.id} value={m.id}>{m.definition.name}</option>)}</select><button className={button} disabled={!exceptionModel} onClick={()=>saveSelection({...selection,exceptions:{...selection.exceptions,[exceptionTask]:exceptionModel}})}>保存例外</button></div><ul>{Object.entries(selection.exceptions).sort(([a],[b])=>a.localeCompare(b)).map(([task,id])=><li key={task} className="flex justify-between items-center gap-3 py-3 text-xs border-t border-slate-100 dark:border-slate-800"><div className="min-w-0 break-words"><strong>{taskLabel(task)} · Content 执行</strong><p className="mt-1">{modelName(id)}{!eligible(models.find(m=>m.id===id),task.split(':')[1])&&<span className="text-red-600"> · 缺少执行适配</span>}</p><details className="text-slate-500 mt-1"><summary>原始键</summary><code className="break-all">{task}</code></details></div><button className={button} onClick={()=>{const exceptions={...selection.exceptions};delete exceptions[task];void saveSelection({...selection,exceptions})}}>移除</button></li>)}</ul></fieldset></details>
    <footer className="sticky bottom-0 z-10 rounded-xl border border-slate-200 dark:border-slate-700 bg-white/95 dark:bg-slate-900/95 shadow-lg p-3 flex flex-wrap items-center gap-2"><span className="text-xs text-slate-500 mr-auto">{busy?'正在处理…':`草稿 r${data.draft?.revision||0} · ${data.draft?'已保存':'未初始化'}`}{report&&<span className="block">{report.passed?'当前草稿预检通过':'当前草稿预检未通过'}</span>}</span><button className={button} disabled={busy||!data.draft||init?.complete===false||(!data.current.active&&!init?.complete)} onClick={()=>action('validate')}>测试并预检</button><button className={primary} disabled={busy||!report?.passed} onClick={()=>action('publish',{validationId:report.id})}>发布配置</button><details className="relative"><summary className={button+' cursor-pointer'}>更多</summary><div className="absolute bottom-full right-0 mb-2 w-60 rounded-xl border bg-white dark:bg-slate-900 p-3 shadow-lg"><label className="text-xs">恢复历史版本到草稿<select aria-label="恢复历史版本" disabled={busy} className={input+' mt-2'} value="" onChange={e=>{const r=data.revisions.find((r:any)=>r.version===Number(e.target.value));if(r)void saveSelection(r.configuration)}}><option value="">选择历史版本</option>{data.revisions.map((r:any)=><option key={r.version} value={r.version}>版本 v{r.version}</option>)}</select></label></div></details></footer>
   </>}
   {tab===1&&<>
    <div className="flex flex-wrap justify-between items-center gap-3"><p className="text-sm text-slate-500">{filtered.length} 个模型 · 每页 12 个</p><button className={primary} disabled={busy} onClick={()=>setEditor(null)}>＋ 添加模型</button></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-2"><input aria-label="搜索模型" placeholder="搜索名称、模型 ID、供应商" className={input} value={filters.search} onChange={e=>changeFilter('search',e.target.value)}/><select aria-label="筛选供应商" className={input} value={filters.provider} onChange={e=>changeFilter('provider',e.target.value)}><option value="">全部供应商</option>{[...new Set(connections.map(c=>c.name))].sort().map(name=><option key={name}>{name}</option>)}</select><select aria-label="筛选能力" className={input} value={filters.capability} onChange={e=>changeFilter('capability',e.target.value)}><option value="">全部能力</option>{Object.entries(modelCapabilityLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select aria-label="筛选状态" className={input} value={filters.status} onChange={e=>changeFilter('status',e.target.value)}>{[['','全部（非历史目录）'],['current','当前使用'],['draft','草稿使用'],['unused','未选择'],['disabled','停用'],['history','历史版本']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.slice((currentPage-1)*12,currentPage*12).map(model=>{
     const d=model.definition,c=connections.find(c=>c.id===model.connectionId),proof=data.validations.find((v:any)=>v.report.models?.some((m:any)=>m.id===model.id)),live=modelUses(data.current.selection,model.id),draft=modelUses(selection,model.id),uses=[...live.map(s=>`生效：${s}`),...draft.map(s=>`草稿：${s}`)]
     return <article key={model.id} className={panel+' flex flex-col gap-3 bg-slate-50/40 dark:bg-slate-950/20'}><div className="flex justify-between items-start gap-2"><h3 className="font-bold text-sm break-words min-w-0">{d.name}</h3><span className="text-xs text-slate-500 shrink-0">{d.isEnabled===false?'停用':superseded.has(model.id)?'历史版本':live.length?'当前使用':draft.length?'草稿使用':'未选择'}</span></div><p className="text-xs font-mono break-all text-slate-500">{d.modelName}</p><p className="text-xs text-slate-500 break-words">{c?.name} · {model.connectionId.slice(0,8)}</p><div className="flex flex-wrap gap-1">{d.capabilities.map((cap:string)=><span key={cap} className="rounded bg-slate-100 dark:bg-slate-800 px-2 py-1 text-xs">{modelCapabilityLabels[cap]||cap}</span>)}</div><p className="text-xs text-slate-500">最近关联预检：{proof?(proof.report.passed?'通过':'未全部通过'):'尚未验证'}</p><div className="text-xs space-y-1 break-words">{uses.slice(0,2).map((s,i)=><p key={i}>{s}</p>)}{uses.length>2&&<p className="text-slate-500">另有 {uses.length-2} 项用途，见详情</p>}{!uses.length&&<p className="text-slate-500">未加入生效配置或草稿</p>}</div><details className="text-xs break-all mt-auto"><summary className="cursor-pointer text-slate-500">连接与用途详情</summary><div className="space-y-2 mt-2"><p>协议：{c?.protocol}</p><p>地址：{c?.baseUrl}</p><p>密钥：{c?.maskedSecret||'已保存'}</p><p>关联预检时间：{date(proof?.createdAt)}</p>{uses.map((s,i)=><p key={i}>{s}</p>)}</div></details><button className={button+' self-end'} disabled={busy} onClick={()=>setEditor(model)}>编辑模型</button></article>
    })}</div>
    {!filtered.length&&<div className={panel+' text-center text-sm text-slate-500'}>没有符合条件的模型。<button className={button+' ml-2'} onClick={()=>{setFilters({search:'',provider:'',capability:'',status:''});setPage(1)}}>清除筛选</button></div>}
    <nav aria-label="模型分页" className="flex justify-center items-center gap-3"><button className={button} disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>上一页</button><span className="text-sm">{currentPage} / {pages}</span><button className={button} disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>下一页</button></nav>
   </>}
   {tab===2&&<>
    <section className={panel}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-sm">初始化检查 · {init?(init.complete?'完成':'尚未完成'):'尚未初始化'}</h3><p className="text-xs text-slate-500 mt-2">已导入 {init?.importedModels||0} 个模型 / {init?.connections||0} 个连接 · {date(init?.checkedAt)}</p></div>{!data.current.active&&<button className={button} disabled={busy} onClick={()=>action('import')}>{init?'重新检查并初始化':'初始化已有配置'}</button>}</div>{issues.map((g,i)=><details key={i} className="mt-3 rounded-lg border border-amber-200 bg-amber-50 dark:bg-amber-950/20 p-3 text-xs break-words"><summary className="cursor-pointer text-amber-900 dark:text-amber-200">{g.category} · {g.label}（{g.items.length} 项）</summary><ul className="list-disc pl-4 mt-2 space-y-1">{g.items.map((s,i)=><li key={i}>{s}</li>)}</ul></details>)}</section>
    {!!init?.pending?.length&&<details className={panel}><summary className="text-sm font-semibold cursor-pointer">待配置记录 · {init.pending.length} 项（不阻塞发布）</summary><p className="text-xs text-slate-500 my-3">已排除出本次发布，未创建占位密钥。使用前需补齐配置并重新验证发布。</p><ul className="text-xs space-y-2 break-words">{init.pending.map((p:any,i:number)=><li key={i}>{p.kind==='model'?`${p.name||p.legacyId} / ${p.modelName}：缺少密钥或地址`:`${taskLabel(`${p.platform}:${p.task}`)}：可选任务尚未配置`}</li>)}</ul></details>}
    <section className={panel}><h3 className="font-bold text-sm">{report?'本次草稿预检':'最近一次预检'}</h3><p className="text-xs text-slate-500 mt-2">{report?(report.passed?'本次草稿预检通过':'本次草稿预检未通过'):`${date(latest?.createdAt)} · 历史结果不代表当前草稿通过`}</p><ul className="mt-3 text-sm space-y-2">{Object.entries(latestReport?.checks||{}).map(([key,ok])=><li key={key} className="break-words"><span>{({'text':'普通文本','json':'业务 JSON','body_composition':'正文生成','conversation':'多轮对话','tools':'工具调用'} as Record<string,string>)[key]||key.replace('system.','')}：{ok?'通过':'未通过'}</span>{latestReport.errors?.[key]&&<p className="text-xs text-red-600 mt-1">{latestReport.errors[key]}</p>}</li>)}</ul>{latestReport?.tasks?.map((t:any,i:number)=><div key={i} className="text-xs border-t py-2 break-words">{t.source} → {t.executor} · {taskLabel(t.task)}{t.platform?` / ${t.platform}`:''} · {t.modelName||'—'} · {t.version===-1?'草稿':`v${t.version}`} · {t.passed?'通过':t.error}</div>)}{latestReport&&<details className="mt-3 text-xs"><summary className="cursor-pointer">原始预检 JSON</summary><pre className="overflow-auto max-h-72 mt-2">{JSON.stringify(latestReport,null,2)}</pre></details>}</section>
    <section className={panel}><h3 className="font-bold text-sm">当前版本调用</h3><div className="grid sm:grid-cols-3 gap-3 mt-3">{['kanban','content','mm'].map(system=>{const call=data.current.active?data.calls.find((c:any)=>c.source===system&&c.version===data.current.version):null;return <div key={system} className="text-xs break-words"><strong>{system.toUpperCase()}</strong><p className="mt-1 text-slate-500">{call?`${call.targetModel} · ${call.status}`:'暂无当前版本调用记录'}</p></div>})}</div><h4 className="font-semibold text-sm mt-5 mb-2">最近调用记录</h4><div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{['时间','系统 / 任务','目标 / 响应模型','版本','结果'].map(s=><th key={s} className="p-2 whitespace-nowrap">{s}</th>)}</tr></thead><tbody>{data.calls.map((c:any,i:number)=><tr key={c.id||i} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2 whitespace-nowrap">{date(c.createdAt)}</td><td className="p-2">{taskLabel(`${c.source}:${c.task}`)}<br/>{c.source} → {c.executor||c.source}</td><td className="p-2 break-all">{c.targetModel}<br/>{c.responseModel||'未提供'}</td><td className="p-2">{c.version??'旧配置'}</td><td className="p-2">{c.status}</td></tr>)}</tbody></table></div>{!data.calls.length&&<p className="text-xs text-slate-500 py-3">暂无调用记录</p>}<details className="text-xs mt-3"><summary className="cursor-pointer">原始调用 JSON</summary><pre className="overflow-auto max-h-72 mt-2">{JSON.stringify(data.calls,null,2)}</pre></details></section>
   </>}
  </div>}
  {busy&&<p role="status" className="px-5 pb-4 text-xs">正在处理，请稍候…</p>}
  {editor!==undefined&&<ModelVersionEditor model={editor} connections={connections} busy={busy} error={error} onClose={()=>{if(!busy)setEditor(undefined)}} onSave={model=>action('save-model',{model})}/>}
 </section>
}
