'use client'
import { useEffect, useRef, useState } from 'react'
import type { UserRecord } from './UsersTab'
import type { RoleDefinition } from '@/lib/role-permissions/contract'
import RolePermissionEditor from './RolePermissionEditor'
type BusinessRole = 'BRAND_OWNER' | 'AMC_PRINCIPAL' | 'BD' | 'RESEARCHER'
type Props = { users: UserRecord[]; loading: boolean; actionLoading: Record<string,string>; onViewAccess: (role: string) => void; onRoleToggle: (user: UserRecord) => Promise<void>; onToggleBusinessRole: (user: UserRecord, role: BusinessRole) => void; onRefresh: () => Promise<void> }
export default function UserGroupsPanel({ users, onViewAccess, onRoleToggle, onToggleBusinessRole, onRefresh }: Props) {
 const [roles,setRoles]=useState<RoleDefinition[]>([]), [selected,setSelected]=useState('ADMIN'), [search,setSearch]=useState('')
 const [ready,setReady]=useState(false), [error,setError]=useState(''), [busy,setBusy]=useState(false), [adding,setAdding]=useState('')
 const [form,setForm]=useState<null | {mode:'create'|'edit';name:string;description:string;copyFrom:string}>(null)
 const [dirty,setDirty]=useState(false)
 const [tab,setTab]=useState<'members'|'permissions'>('members')
 const [memberSearch,setMemberSearch]=useState(''), [page,setPage]=useState(1)
 const [addOpen,setAddOpen]=useState(false), [addSearch,setAddSearch]=useState('')
 const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(addOpen)dialog.current?.showModal();else dialog.current?.close()},[addOpen])
 useEffect(()=>{setPage(1);setMemberSearch('');setTab('members');setAdding('');setAddOpen(false)},[selected])
 async function load(){const r=await fetch('/api/admin/roles',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);setRoles(data.roles);setReady(data.contentReady)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty])
 const role=roles.find(r=>r.id===selected)
 const members=users.filter(u=>u.type==='HUMAN'&&(selected==='ADMIN'?u.role==='ADMIN':u.businessRoles.some(r=>r.role===selected)))
 const matches=(u:UserRecord,q:string)=>[u.nickname,u.email].some(v=>v?.toLowerCase().includes(q.trim().toLowerCase()))
 const filtered=members.filter(u=>matches(u,memberSearch))
 const pages=Math.max(1,Math.ceil(filtered.length/10)), currentPage=Math.min(page,pages)
 const visible=filtered.slice((currentPage-1)*10,currentPage*10)
 const candidates=users.filter(u=>u.type==='HUMAN'&&!members.some(m=>m.id===u.id)&&matches(u,addSearch))
 function chooseRole(id:string){if(id!==selected&&leave()){setSelected(id);setForm(null)}}
 function leave(){if(dirty&&!window.confirm('放弃当前未保存的权限修改？'))return false;setDirty(false);return true}
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function request(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw Error(data.error);return data}
 async function saveForm(){if(!form)return;await action(async()=>{const data=await request(form.mode==='create'?'/api/admin/roles':`/api/admin/roles/${selected}`,form.mode==='create'?'POST':'PATCH',{name:form.name,description:form.description,...(form.mode==='create'?{...(form.copyFrom?{copyFrom:form.copyFrom}:{})}:{expectedVersion:role?.version})});await load();setSelected(data.id);setForm(null)})}
 async function member(user:UserRecord,present:boolean){if(!role)return;await action(async()=>{if(role.builtIn){if(selected==='ADMIN')await onRoleToggle(user);else await onToggleBusinessRole(user,selected as BusinessRole)}else await request(`/api/admin/roles/${selected}/members/${user.id}`,present?'PUT':'DELETE');await onRefresh();await load();setAdding('');setAddOpen(false)})}
 return <div className="space-y-4">
  <div className="flex flex-wrap gap-3 items-center"><h3 className="font-bold">用户组与角色</h3><input aria-label="搜索角色组" placeholder="搜索角色组" value={search} onChange={e=>setSearch(e.target.value)} className="border rounded-lg p-2 text-sm bg-transparent"/><button disabled={busy||!ready} className="ml-auto rounded-lg bg-blue-600 text-white px-4 py-2 disabled:opacity-40" onClick={()=>{if(leave())setForm({mode:'create',name:'',description:'',copyFrom:''})}}>新增角色组</button><button onClick={()=>action(load)} disabled={busy}>刷新角色</button></div>
  {!ready&&<p className="text-sm text-amber-700">Content 权限协议 2 未就绪，暂不能创建、启用或添加成员。</p>}
  {error&&<p role="alert" className="text-red-600">{error}</p>}
  {form&&<section aria-label={form.mode==='create'?'新增角色组':'编辑角色资料'} className="border rounded-xl bg-white dark:bg-slate-900 p-4 space-y-3"><h4 className="font-bold">{form.mode==='create'?'新增角色组':'编辑角色资料'}</h4><label className="block">名称<input aria-label="角色名称" maxLength={60} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="ml-2 border rounded p-2 bg-transparent"/></label><label className="block">说明<textarea aria-label="角色说明" maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="ml-2 border rounded p-2 bg-transparent"/></label>{form.mode==='create'&&<label className="block">初始权限<select aria-label="复制角色权限" value={form.copyFrom} onChange={e=>setForm({...form,copyFrom:e.target.value})} className="ml-2 border rounded p-2 dark:bg-slate-900"><option value="">空白（无权限）</option>{roles.filter(r=>r.enabled&&r.id!=='ADMIN').map(r=><option value={r.id} key={r.id}>复制 {r.name}</option>)}</select><p className="text-xs text-slate-500 mt-2">复制当前权限，之后独立维护；不复制成员或品牌授权。</p></label>}<button disabled={busy||!form.name.trim()} onClick={saveForm} className="rounded bg-blue-600 text-white px-4 py-2 disabled:opacity-40">{busy?'保存中…':'保存角色'}</button><button disabled={busy} onClick={()=>setForm(null)} className="ml-3">取消</button></section>}
  <div className="grid lg:grid-cols-[240px_minmax(0,1fr)] gap-4 items-start"><select aria-label="选择角色组" value={selected} onChange={e=>chooseRole(e.target.value)} disabled={busy} className="lg:hidden border rounded-lg p-2 bg-transparent">{roles.filter(r=>r.id===selected||r.name.toLowerCase().includes(search.toLowerCase())).map(r=><option key={r.id} value={r.id}>{r.name}{!r.enabled?"（已停用）":""}</option>)}</select><aside className="hidden lg:block border rounded-xl p-3 space-y-4 max-h-[calc(100dvh-240px)] overflow-y-auto sticky top-4">{[true,false].map(builtIn=><section key={String(builtIn)}><h4 className="text-xs text-slate-500 mb-2">{builtIn?'系统预设':'自定义角色'}</h4>{roles.filter(r=>r.builtIn===builtIn&&r.name.toLowerCase().includes(search.toLowerCase())).map(r=><button key={r.id} disabled={busy} onClick={()=>chooseRole(r.id)} className={`w-full text-left rounded-lg p-3 text-sm ${r.id===selected?'bg-blue-600 text-white':'hover:bg-slate-100'}`}>{r.name} {!r.enabled&&'（已停用）'}<span className="float-right">{r.id==='ADMIN'?users.filter(u=>u.role==='ADMIN'&&u.type==='HUMAN').length:r.memberCount||0} 人</span></button>)}</section>)}</aside>
   <section className="border rounded-xl p-4 space-y-4">{role?<><h3 className="font-bold">{role.name} {!role.enabled&&'（已停用，不参与授权）'}</h3><p className="text-sm text-slate-500">{role.description||'功能权限与品牌授权分别管理。'}</p><div className="flex flex-wrap gap-3"><button className="text-blue-600" onClick={()=>{if(leave())onViewAccess(role.id)}}>查看权限</button>{!role.builtIn&&<><button disabled={busy} onClick={()=>setForm({mode:'edit',name:role.name,description:role.description,copyFrom:''})}>编辑名称和说明</button><button disabled={busy||(!role.enabled&&!ready)} onClick={()=>{if(window.confirm(`${role.enabled?'停用':'重新启用'}“${role.name}”，影响 ${role.memberCount||0} 个直接成员及其已有委托账号。${role.enabled?'保留成员和配置，不再授予权限。':'将恢复该角色授权。'}`))action(async()=>{await request(`/api/admin/roles/${role.id}`,'PATCH',{enabled:!role.enabled,expectedVersion:role.version});await load();await onRefresh()})}}>{role.enabled?'停用角色':'重新启用'}</button></>}</div>
   <div className="flex gap-4 border-b" role="tablist" aria-label="角色详情">
    {(['members','permissions'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} className={`py-2 text-sm border-b-2 ${tab===t?'border-blue-600 text-blue-600':'border-transparent'}`} onClick={()=>{if(t!==tab&&leave())setTab(t)}}>{t==='members'?`成员管理（${members.length}）`:'角色权限'}</button>)}
   </div>
   {tab==='members'?<div role="tabpanel" className="space-y-3">
    <div className="flex flex-wrap gap-2"><input aria-label="搜索成员" placeholder="搜索姓名或邮箱" value={memberSearch} onChange={e=>{setMemberSearch(e.target.value);setPage(1)}} className="border rounded-lg p-2 text-sm bg-transparent min-w-0 flex-1"/><button disabled={busy||!role.enabled||(!role.builtIn&&!ready)} onClick={()=>{setAddSearch('');setAdding('');setAddOpen(true)}} className="rounded-lg bg-blue-600 text-white px-3 py-2 text-sm disabled:opacity-40">添加成员</button></div>
    <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-xs text-slate-500 border-b"><tr><th className="py-2">成员</th><th className="py-2 hidden sm:table-cell">邮箱</th><th className="py-2 text-right">操作</th></tr></thead><tbody>{visible.map(u=><tr key={u.id} className="border-b last:border-0"><td className="py-2 pr-3"><span className="break-all">{u.nickname&&u.nickname!==u.email?u.nickname:<><span className="sm:hidden">{u.email}</span><span className="hidden sm:inline">—</span></>}</span>{u.nickname&&u.nickname!==u.email&&<span className="block text-xs text-slate-500 sm:hidden break-all">{u.email}</span>}</td><td className="py-2 pr-3 hidden sm:table-cell break-all">{u.email}</td><td className="py-2 text-right"><button disabled={busy} onClick={()=>{if(window.confirm(`将 ${u.nickname||u.email} 移出该角色？`))member(u,false)}} className="text-red-600 disabled:opacity-40 whitespace-nowrap">移除</button></td></tr>)}</tbody></table></div>
    {!filtered.length&&<p className="text-sm text-slate-500 py-6 text-center">{members.length?'没有匹配的成员':'暂无成员，创建角色不会自动加入账号。'}</p>}
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>共 {members.length} 人{memberSearch.trim()?`，匹配 ${filtered.length} 人`:''} · 每页 10 人</span><div className="flex items-center gap-3"><button aria-label="上一页成员" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)} className="border rounded px-2 py-1 disabled:opacity-40">上一页</button><span>{currentPage} / {pages}</span><button aria-label="下一页成员" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)} className="border rounded px-2 py-1 disabled:opacity-40">下一页</button></div></div>
   </div>:<div role="tabpanel" className="space-y-3">{role.id==='ADMIN'?<p className="text-sm text-slate-500">系统固定权限，不提供编辑。</p>:<><p className="text-sm text-slate-500">{!role.enabled?'以下为保存的配置，角色停用期间不参与授权。':'以下权限适用于该角色全部有效成员。'}</p><RolePermissionEditor key={role.id} role={role.id} affectedUsers={members.length} onDirtyChange={setDirty}/></>}</div>}
   </>:<p>正在加载角色…</p>}</section>
  </div>
  <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setAddOpen(false)}} onClose={()=>setAddOpen(false)} aria-labelledby="add-members-title" className="m-auto w-[calc(100%-2rem)] max-w-lg rounded-xl border p-5 bg-white dark:bg-slate-900 dark:text-white backdrop:bg-black/40">
   <div className="flex justify-between items-center mb-4"><h3 id="add-members-title" className="font-bold">添加成员 · {role?.name}</h3><button disabled={busy} onClick={()=>setAddOpen(false)} aria-label="关闭添加成员">关闭</button></div>
   <input autoFocus aria-label="搜索可添加账号" placeholder="搜索姓名或邮箱" value={addSearch} onChange={e=>setAddSearch(e.target.value)} className="w-full border rounded-lg p-2 bg-transparent text-sm"/>
   <div className="max-h-64 overflow-y-auto my-3">{candidates.map(u=><label key={u.id} className="flex gap-2 items-center border-b py-2 text-sm"><input type="radio" name="new-member" value={u.id} checked={adding===u.id} onChange={()=>setAdding(u.id)}/><span className="break-all">{u.nickname&&u.nickname!==u.email?u.nickname+' · ':''}{u.email}</span></label>)}{!candidates.length&&<p className="py-6 text-center text-sm text-slate-500">没有可添加的匹配账号</p>}</div>
   {error&&<p role="alert" className="text-red-600 text-sm mb-3">{error}</p>}
   <button disabled={busy||!adding} onClick={()=>{const user=users.find(u=>u.id===adding);if(user)member(user,true)}} className="bg-blue-600 text-white rounded-lg px-4 py-2 text-sm disabled:opacity-40">{busy?'正在加入…':'加入成员'}</button>
  </dialog>
 </div>
}
