'use client'

import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, ChevronLeft, ChevronRight, Edit3, ExternalLink, RefreshCw, Search, Send, Store, Users, X } from 'lucide-react'
import { fetchOperationsJson } from '@/lib/brand-operations/client'
import { countryLabel } from '@/lib/brand-operations/country'
import { useI18n } from '@/lib/i18n'
import type { listOperations } from '@/lib/brand-operations/service'

type Data = Awaited<ReturnType<typeof listOperations>>
type Brand = Data['rows'][number]
type Account = Brand['socialAccounts'][number]
const statuses: Record<string, [string, string]> = { ACTIVE: ['生效中', 'Active'], PENDING: ['待激活', 'Pending'], EXPIRED: ['已到期', 'Expired'], CANCELLED: ['已取消', 'Cancelled'], FAILED: ['失败', 'Failed'], UPCOMING: ['未开始', 'Upcoming'] }
const profileHref = (value: string | null) => { if (!value) return null; try { const u = new URL(value); return ['http:', 'https:'].includes(u.protocol) ? u.href : null } catch { return null } }

export default function BrandOperationsView() {
  const { language } = useI18n(); const en = language === 'en'; const t = (zh: string, eng: string) => en ? eng : zh
  const [data, setData] = useState<Data | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [q, setQ] = useState(''), [status, setStatus] = useState(''), [principal, setPrincipal] = useState(''), [sort, setSort] = useState('expiry')
  const [principalOptions, setPrincipalOptions] = useState<Data['principalOptions']>([]), [page, setPage] = useState(1), [refresh, setRefresh] = useState(0), [selectedId, setSelectedId] = useState<string | null>(null)
  const selected = data?.rows.find(row => row.id === selectedId) || null
  useEffect(() => { const abort = new AbortController(); const timer = setTimeout(async () => { setLoading(true); setError(''); try {
    const params = new URLSearchParams({ q, status, principalId: principal, sort, page: String(page) })
    const body = await fetchOperationsJson<Data>(`/api/brand-operations?${params}`, { signal: abort.signal, cache: 'no-store' }, { en }); if (abort.signal.aborted) return
    setData(body); setPrincipalOptions(previous => { const chosen = previous.find(p => p.id === principal); return chosen && !body.principalOptions.some(p => p.id === principal) ? [...body.principalOptions, chosen] : body.principalOptions })
  } catch (e) { if (!abort.signal.aborted) { setData(null); setError(e instanceof Error ? e.message : 'Unable to load brand operations') } } finally { if (!abort.signal.aborted) setLoading(false) } }, 250); return () => { clearTimeout(timer); abort.abort() } }, [q, status, principal, sort, page, refresh, en])
  useEffect(() => { if (!selectedId) return; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setSelectedId(null) }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape) }, [selectedId])
  const date = (value: Date | string | null | undefined, withTime = false) => value ? new Intl.DateTimeFormat(en ? 'en-SG' : 'zh-CN', { timeZone: 'Asia/Singapore', year: 'numeric', month: '2-digit', day: '2-digit', ...(withTime ? { hour: '2-digit', minute: '2-digit' } as const : {}) }).format(new Date(value)) : t('未设置', 'Not set')
  const number = (value: number) => new Intl.NumberFormat(en ? 'en-SG' : 'zh-CN', { notation: Math.abs(value) >= 10000 ? 'compact' : 'standard' }).format(value)
  const control = 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 shadow-sm outline-none transition-colors focus-visible:border-blue-500 focus-visible:ring-2 focus-visible:ring-blue-500/20 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:placeholder:text-slate-500'
  return <section className="h-full overflow-y-auto bg-slate-50 p-3 text-slate-900 dark:bg-slate-950 dark:text-slate-100 md:p-5"><div className="mx-auto max-w-[1700px] space-y-4">
    <header className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold tracking-widest text-blue-700 dark:text-blue-400">{t('主理人工作区', 'PRINCIPAL WORKSPACE')}</p><h1 className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{t('品牌运营看板', 'Brand Operations')}</h1><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{t('集中查看品牌、账号覆盖与综合运营表现', 'Review brands, account coverage and operational performance.')}</p></div><button onClick={() => setRefresh(v => v + 1)} disabled={loading} className={`${control} inline-flex items-center gap-2 disabled:opacity-50`}><RefreshCw size={15} className={loading ? 'animate-spin' : ''} />{t('刷新', 'Refresh')}</button></header>
    {data && !error && <div className="grid grid-cols-2 gap-2 xl:grid-cols-4">{[
      { label: t('订阅品牌', 'Subscribed brands'), value: data.summary.brands, note: t(`${data.summary.accounts} 个账号`, `${data.summary.accounts} accounts`), Icon: Store },
      { label: t('账号链接完整', 'Linked profiles'), value: `${data.summary.linkedAccounts}/${data.summary.accounts}`, note: t('可直接打开主页', 'Direct profile access'), Icon: Users },
      { label: t('需关注品牌', 'Needs attention'), value: data.summary.attentionBrands, note: t('健康或连接异常', 'Health or connection issue'), Icon: AlertTriangle },
      { label: t('本月发布', 'Published this month'), value: data.summary.monthlyPublished, note: `${t('粉丝净增', 'Follower change')} ${data.summary.followerDelta >= 0 ? '+' : ''}${number(data.summary.followerDelta)}`, Icon: Send },
    ].map(({ label, value, note, Icon }) => <div key={label} className="rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between text-xs font-medium text-slate-600 dark:text-slate-400"><span>{label}</span><Icon size={16} className="text-slate-400 dark:text-slate-500" /></div><div className="mt-1 flex items-end justify-between gap-2"><p className="text-2xl font-bold tabular-nums text-slate-950 dark:text-white">{typeof value === 'number' ? number(value) : value}</p><span className="pb-1 text-[11px] text-slate-500 dark:text-slate-400">{note}</span></div></div>)}</div>}
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap gap-2 border-b border-slate-100 p-3 dark:border-slate-800">
      <label className="relative min-w-56 flex-1"><span className="sr-only">{t('搜索', 'Search')}</span><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className={`${control} w-full pl-9`} placeholder={t('搜索品牌、账号、位置或主理人', 'Search brand, account, location or people')} value={q} onChange={e => { setQ(e.target.value); setPage(1) }} /></label>
      <select aria-label={t('订阅状态', 'Subscription status')} className={control} value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}><option value="">{t('全部订阅状态', 'All statuses')}</option>{Object.entries(statuses).map(([key, labels]) => <option key={key} value={key}>{labels[en ? 1 : 0]}</option>)}</select>
      <select aria-label={t('主理人筛选', 'Filter principal')} className={control} value={principal} onChange={e => { setPrincipal(e.target.value); setPage(1) }}><option value="">{t('全部主理人', 'All principals')}</option><option value="unassigned">{t('未分配', 'Unassigned')}</option>{principalOptions.map(p => <option value={p.id} key={p.id}>{p.nickname || p.email}</option>)}</select>
      <select aria-label={t('排序', 'Sort')} className={control} value={sort} onChange={e => { setSort(e.target.value); setPage(1) }}><option value="expiry">{t('合约到期', 'Contract expiry')}</option><option value="published">{t('本月发布', 'Monthly posts')}</option><option value="name">{t('品牌名称', 'Brand name')}</option></select>
    </div>
    {error ? <div role="alert" className="p-12 text-center"><p className="font-medium text-red-700 dark:text-red-400">{error}</p><button onClick={() => setRefresh(v => v + 1)} className="mt-4 rounded-md text-blue-700 outline-none hover:underline focus-visible:ring-2 focus-visible:ring-blue-500/30 dark:text-blue-400">{t('重试', 'Try again')}</button></div> : loading ? <div role="status" className="p-16 text-center text-slate-600 dark:text-slate-400">{t('正在加载品牌运营数据…', 'Loading brand operations…')}</div> : !data?.rows.length ? <div className="p-16 text-center text-slate-600 dark:text-slate-400">{t('没有符合条件的订阅品牌', 'No subscribed brands match these filters')}</div> : <div className="overflow-x-auto"><table className="w-full min-w-[1080px] whitespace-nowrap text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-600 dark:bg-slate-950/40 dark:text-slate-400"><tr>{[t('品牌', 'Brand'), t('运营账号', 'Accounts'), t('综合健康', 'Health'), t('本月发布', 'Monthly posts'), t('粉丝 / 净增', 'Followers / change'), t('品牌主理人', 'Principal'), t('合约到期', 'Contract end')].map(label => <th className="px-3 py-2.5 font-semibold" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 text-slate-800 dark:divide-slate-800 dark:text-slate-200">{data.rows.map(row => <tr key={row.id} className="cursor-pointer hover:bg-blue-50/60 dark:hover:bg-slate-800/40" onClick={event => { if ((event.target as HTMLElement).closest('a, button, input, select') || window.getSelection()?.toString()) return; event.currentTarget.querySelector<HTMLAnchorElement>('a[data-brand-link]')?.click() }}>
      <td className="px-3 py-2.5"><div className="flex items-center gap-2"><a data-brand-link href={data.canManage ? `/admin?tab=brands&brandId=${encodeURIComponent(row.id)}&returnTo=managementOverview` : `/board?tab=dashboard&brandId=${encodeURIComponent(row.id)}&returnTo=managementOverview`} aria-label={`${t('编辑品牌：', 'Edit brand: ')}${row.name}`} className="max-w-48 truncate rounded-sm font-semibold text-slate-950 outline-none hover:text-blue-700 hover:underline focus-visible:ring-2 focus-visible:ring-blue-500/30 dark:text-white dark:hover:text-blue-400" title={row.name}>{row.name}</a><span className="text-xs text-slate-600 dark:text-slate-400">{countryLabel(row.location, en)}</span></div></td>
      <td className="px-3 py-2.5"><button aria-label={`${t('查看账号表现：', 'View account performance: ')}${row.name}`} onClick={() => setSelectedId(row.id)} className="flex items-center gap-1.5 rounded-lg hover:text-blue-600">{row.socialAccounts.length ? <><span className="flex -space-x-1">{row.socialAccounts.slice(0, 3).map(a => <span key={a.id} title={`${a.platformId} · ${a.displayName || a.handle}`} className="inline-flex h-6 min-w-6 items-center justify-center rounded-full border-2 border-white bg-slate-100 px-1 text-[9px] font-bold uppercase dark:border-slate-900 dark:bg-slate-800">{a.platformId.slice(0, 2)}</span>)}</span><span className="text-xs font-medium">{row.accountSummary.totalAccounts} {t('个', 'total')}</span>{row.accountSummary.linkedAccounts < row.accountSummary.totalAccounts && <span className="text-[11px] text-amber-600">{t('缺链接', 'missing links')}</span>}</> : <span className="text-xs font-medium text-amber-600">{t('未配置账号', 'No accounts')}</span>}</button></td>
      <td className="px-3 py-2.5"><button onClick={() => setSelectedId(row.id)} className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-semibold ${row.accountSummary.healthStatus === 'HEALTHY' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}><Activity size={13} />{row.accountSummary.healthScore}</button></td>
      <td className="px-3 py-2.5 font-semibold tabular-nums">{row.monthlyPublished}</td><td className="px-3 py-2.5 tabular-nums"><span className="font-medium">{number(row.accountSummary.followers)}</span><span className={`ml-2 text-xs ${row.accountSummary.followerDelta < 0 ? 'text-red-600' : 'text-emerald-600'}`}>{row.accountSummary.followerDelta >= 0 ? '+' : ''}{number(row.accountSummary.followerDelta)}</span></td>
      <td className="px-3 py-2.5"><span className="block max-w-36 truncate text-slate-700 dark:text-slate-300">{row.principals.map(p => p.nickname || p.email).join('、') || t('未分配', 'Unassigned')}</span></td><td className={`px-3 py-2.5 text-xs tabular-nums ${row.subscription.effectiveStatus === 'EXPIRED' ? 'text-red-700 dark:text-red-400' : 'text-slate-600 dark:text-slate-400'}`} title={`${row.subscription.planName} · ${statuses[row.subscription.effectiveStatus]?.[en ? 1 : 0] || row.subscription.effectiveStatus}`}>{date(row.subscription.contractEndDate)}</td>
    </tr>)}</tbody></table></div>}
    {data && !loading && !error && <footer className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-sm text-slate-600 dark:border-slate-800 dark:text-slate-400"><span>{t(`共 ${data.total} 个品牌 · 第 ${data.page} 页`, `${data.total} brands · Page ${data.page}`)}</span><div className="flex gap-2"><button aria-label={t('上一页', 'Previous page')} className="rounded-lg border border-slate-300 p-2 outline-none hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-blue-500/30 disabled:opacity-30 dark:border-slate-700 dark:hover:bg-slate-800" disabled={data.page <= 1} onClick={() => setPage(data.page - 1)}><ChevronLeft size={16} /></button><button aria-label={t('下一页', 'Next page')} className="rounded-lg border border-slate-300 p-2 outline-none hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-blue-500/30 disabled:opacity-30 dark:border-slate-700 dark:hover:bg-slate-800" disabled={data.page * data.pageSize >= data.total} onClick={() => setPage(data.page + 1)}><ChevronRight size={16} /></button></div></footer>}</div>
    <p className="text-xs leading-5 text-slate-600 dark:text-slate-400">{data ? `${date(data.period.start)} — ${date(data.period.end, true)} · Asia/Singapore。` : ''}{t('健康分：连接 30 分、主页链接 15 分、发布活跃度 40 分（每账号每月 4 条满分）、粉丝趋势 15 分。低于 60 分或存在停用账号时标记需关注。', 'Health score: connection 30, profile links 15, publishing 40 (four posts per account), follower trend 15. Below 60 or a disabled account needs attention.')}</p>
  </div>{selected && <AccountPanel brand={selected} canManage={Boolean(data?.canManage)} en={en} close={() => setSelectedId(null)} date={date} number={number} refresh={() => setRefresh(v => v + 1)} />}</section>
}

function AccountPanel({ brand, canManage, en, close, date, number, refresh }: { brand: Brand; canManage: boolean; en: boolean; close: () => void; date: (v: Date | string | null | undefined, time?: boolean) => string; number: (v: number) => string; refresh: () => void }) {
  const t = (zh: string, eng: string) => en ? eng : zh
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" onMouseDown={e => { if (e.target === e.currentTarget) close() }}><aside role="dialog" aria-modal="true" aria-labelledby="account-panel-title" className="h-full w-full max-w-2xl overflow-y-auto bg-slate-50 shadow-2xl dark:bg-slate-950"><header className="sticky top-0 z-10 flex justify-between border-b bg-white px-5 py-4 dark:border-slate-800 dark:bg-slate-900"><div><p className="text-xs font-medium text-blue-600">{t('账号综合表现', 'Account performance')}</p><h2 id="account-panel-title" className="mt-1 text-xl font-bold">{brand.name}</h2><p className="mt-1 text-xs text-slate-500">{brand.accountSummary.totalAccounts} {t('个账号', 'accounts')} · {t('健康分', 'health')} {brand.accountSummary.healthScore}</p></div><button aria-label={t('关闭账号详情', 'Close account details')} onClick={close} className="rounded-lg p-2"><X size={19} /></button></header><div className="grid grid-cols-3 gap-2 p-4"><Metric label={t('粉丝总量', 'Followers')} value={number(brand.accountSummary.followers)} /><Metric label={t('本月发布', 'Monthly posts')} value={number(brand.monthlyPublished)} /><Metric label={t('粉丝净增', 'Follower change')} value={`${brand.accountSummary.followerDelta >= 0 ? '+' : ''}${number(brand.accountSummary.followerDelta)}`} /></div><div className="space-y-3 px-4 pb-6">{brand.socialAccounts.length ? brand.socialAccounts.map(a => <AccountCard key={a.id} brandId={brand.id} account={a} canManage={canManage} en={en} date={date} number={number} refresh={refresh} />) : <div className="rounded-xl border border-dashed border-amber-300 bg-amber-50 p-8 text-center text-sm text-amber-800">{t('该品牌尚未配置运营账号，请先在品牌设置中绑定账号。', 'No account is configured. Bind one in brand settings first.')}</div>}</div></aside></div>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold tabular-nums">{value}</p></div> }

function AccountCard({ brandId, account, canManage, en, date, number, refresh }: { brandId: string; account: Account; canManage: boolean; en: boolean; date: (v: Date | string | null | undefined, time?: boolean) => string; number: (v: number) => string; refresh: () => void }) {
  const t = (zh: string, eng: string) => en ? eng : zh; const [editing, setEditing] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState('')
  const [form, setForm] = useState({ handle: account.handle === 'unconfigured' ? '' : account.handle, displayName: account.displayName || '', profileUrl: account.profileUrl || '' })
  const url = profileHref(account.profileUrl), missingName = !account.displayName && (!account.handle || account.handle === 'unconfigured'), disconnected = Boolean(account.disabledReason) || ['DISABLED', 'DISCONNECTED', 'ERROR', 'EXPIRED'].includes(account.connectionStatus.toUpperCase())
  const save = async () => { if (!form.handle.trim()) { setError(t('请填写账号名称或 handle', 'Enter an account handle')); return } setSaving(true); setError(''); try { await fetchOperationsJson(`/api/brands/${encodeURIComponent(brandId)}/accounts/${encodeURIComponent(account.id)}?public=1`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ handle: form.handle.trim(), displayName: form.displayName.trim(), profileUrl: form.profileUrl.trim() }) }, { en }); setEditing(false); refresh() } catch (e) { setError(e instanceof Error ? e.message : t('保存失败', 'Save failed')) } finally { setSaving(false) } }
  return <article className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold uppercase dark:bg-slate-800">{account.platformId}</span><span className={`rounded-full px-2 py-1 text-[11px] ${disconnected ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}>{disconnected ? t('连接异常', 'Connection issue') : t('已连接', 'Connected')}</span></div><h3 className="mt-2 font-semibold">{account.displayName || (account.handle !== 'unconfigured' ? account.handle : t('名称待补充', 'Name missing'))}</h3><p className="text-xs text-slate-500">{account.handle && account.handle !== 'unconfigured' ? `@${account.handle.replace(/^@/, '')}` : t('Handle 待补充', 'Handle missing')}</p></div><div className="flex gap-2">{url ? <a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs hover:text-blue-600"><ExternalLink size={14} />{t('打开账号', 'Open profile')}</a> : <span className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700">{t('链接待补充', 'Link missing')}</span>}{canManage && <button onClick={() => setEditing(v => !v)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs hover:text-blue-600"><Edit3 size={14} />{t('编辑', 'Edit')}</button>}</div></div>
    {(missingName || !url || disconnected) && <div className="mt-3 flex gap-2">{missingName && <span className="rounded bg-amber-50 px-2 py-1 text-[11px] text-amber-700">{t('缺少名称', 'Missing name')}</span>}{!url && <span className="rounded bg-amber-50 px-2 py-1 text-[11px] text-amber-700">{t('缺少有效主页链接', 'Missing valid link')}</span>}{account.disabledReason && <span className="rounded bg-red-50 px-2 py-1 text-[11px] text-red-700">{account.disabledReason}</span>}</div>}
    <dl className="mt-4 grid grid-cols-2 gap-3 border-t pt-3 text-sm sm:grid-cols-4 dark:border-slate-800">{[[t('粉丝', 'Followers'), number(account.followerCount || 0)], [t('净增', 'Change'), `${(account.followerDelta || 0) >= 0 ? '+' : ''}${number(account.followerDelta || 0)}`], [t('本月发布', 'Monthly posts'), number(account.monthlyPublished)], [t('评分', 'Rating'), account.ratingScore == null ? '—' : account.ratingScore.toFixed(1)], [t('最近发布', 'Last published'), account.lastPublishedAt ? date(account.lastPublishedAt, true) : '—'], [t('数据快照', 'Snapshot'), account.snapshotAt ? date(account.snapshotAt, true) : '—']].map(([label, value]) => <div key={label}><dt className="text-[11px] text-slate-500">{label}</dt><dd className="font-medium tabular-nums">{value}</dd></div>)}</dl>
    {editing && <div className="mt-4 space-y-3 rounded-lg bg-slate-50 p-3 dark:bg-slate-950"><div className="grid gap-3 sm:grid-cols-2"><Field label={t('账号名称 / Handle', 'Account handle')} value={form.handle} set={value => setForm({ ...form, handle: value })} placeholder="account_name" /><Field label={t('显示名称', 'Display name')} value={form.displayName} set={value => setForm({ ...form, displayName: value })} /></div><Field label={t('账号主页链接', 'Profile URL')} value={form.profileUrl} set={value => setForm({ ...form, profileUrl: value })} placeholder="https://…" />{error && <p role="alert" className="text-xs text-red-600">{error}</p>}<div className="flex justify-end gap-2"><button onClick={() => { setEditing(false); setError('') }} className="px-3 py-2 text-xs">{t('取消', 'Cancel')}</button><button onClick={save} disabled={saving} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-medium text-white disabled:opacity-50">{saving ? t('保存中…', 'Saving…') : t('保存账号资料', 'Save account')}</button></div></div>}
  </article>
}
function Field({ label, value, set, placeholder }: { label: string; value: string; set: (v: string) => void; placeholder?: string }) { return <label className="block text-xs text-slate-600">{label}<input value={value} onChange={e => set(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" placeholder={placeholder} /></label> }
